### ISSUE TITLE
[BUG] Yarn issue

### ISSUE THREAD

**Issue by benzon** [Bentix-cs/fivem-greenscreener#10]
When i try to start this resource, this is the error i get, unsure why it is not working could use some help.
![bugscreen](https://github.com/Bentix-cs/fivem-greenscreener/assets/3528000/099bcfd0-06e3-47a0-ad5b-1be9d4e15250)

**Comment by BubbleDudeAT** [comment]
Same here

**Comment by TGIANN** [comment]
#11 change ml-regression-exponential version 2.1.2 to 2.1.0

**Comment by benzon** [comment]
> #11 change ml-regression-exponential version 2.1.2 to 2.1.0

Yep that works!
