### ISSUE TITLE
Maybe bug with greenscreen

### ISSUE THREAD

**Issue by XyreDev** [Bentix-cs/fivem-greenscreener#5]
Hi, i used screenshotobject command and it didnt greenscreen it and cut the picture from greenscreen, also my customscreenshot command didnt work.

Btw i little bit modified the screenshotobject command to support model names

Code:
```
RegisterCommand('screenshotobject', async (source, args) => {
	const modelHash = isNaN(Number(args[0])) ? GetHashKey(args[0]) : Number(args[0]);
	const ped = GetPlayerPed(-1);

	if (!stopWeatherResource()) return;

	DisableIdleCamera(true);

	await Delay(100);

	if (!IsModelValid(modelHash)) return;

	if (!HasModelLoaded(modelHash)) {
		RequestModel(modelHash);
		while (!HasModelLoaded(modelHash)) {
			await Delay(100);
		}
	}

	SetEntityCoords(ped, config.greenScreenHiddenSpot.x, config.greenScreenHiddenSpot.y, config.greenScreenHiddenSpot.z, false, false, false);

	SetPlayerControl(playerId, false);

	const object = CreateObjectNoOffset(modelHash, config.greenScreenPosition.x, config.greenScreenPosition.y, config.greenScreenPosition.z, false, true, true);

	SetEntityRotation(object, Number(args[1]) || config.greenScreenRotation.x, Number(args[2]) || config.greenScreenRotation.y, Number(args[3]) || config.greenScreenRotation.z, 0, false);

	FreezeEntityPosition(object, true);

	await Delay(50);

	await takeScreenshotForObject(object, modelHash);

	DeleteEntity(object);
	SetPlayerControl(playerId, true);
	SetModelAsNoLongerNeeded(modelHash);
	startWeatherResource();
	DestroyAllCams(true);
	DestroyCam(cam, true);
	RenderScriptCams(false, false, 0, true, false, 0);
	cam = null;
});
```

**Comment by Bentix-cs** [comment]
Did you check if the node modules were installed?
What was the exact command that you used for the custom screenshot?

**Comment by Bentix-cs** [comment]
Also, did you get any errors in the console?

**Comment by XyreDev** [comment]
Hi, yes i have node_modules folder and there is many other folders so i assume it were installed. I saw 0 errors in client/server console. Also i used the customscreenshot command that is on your readme.md file! Hope this helps

**Comment by XyreDev** [comment]
oh i think why the greenscreen didnt work, i didnt have this: https://github.com/jimgordon20/jim_g_green_screen but that doesnt explain why my customscreenshot command dont work. Also can you please add in dependency that ymap thanks

**Comment by XyreDev** [comment]
I managed to fix the command. The command that i used and was in readme: `/customscreenshot 11 17 clothing male {"fov": 55, "rotation": { "x": 0, "y": 0, "z": 15}, "zPos": 0.26}`

client.js:
```
RegisterCommand('customscreenshot', async (source, args) => {

	const type = args[2].toUpperCase();
	const component = parseInt(args[0]);
	let drawable = args[1].toLowerCase() == 'all' ? args[1].toLowerCase() : parseInt(args[1]);
	let prop = args[1].toLowerCase() == 'all' ? args[1].toLowerCase() : parseInt(args[1]);
	const gender = args[3].toLowerCase();
	let cameraSettings = "";


	let modelHashes;

	if (gender == 'male') {
		modelHashes = [GetHashKey('mp_m_freemode_01')];
	} else if (gender == 'female') {
		modelHashes = [GetHashKey('mp_f_freemode_01')];
	} else {
		modelHashes = [GetHashKey('mp_m_freemode_01'), GetHashKey('mp_f_freemode_01')];
	}

	if (args[4] != null) {
		for (let i = 4; i < args.length; i++) {
			console.log(i, args[i])
			cameraSettings += args[i] + ' ';
		}
		console.log(cameraSettings)
		cameraSettings = JSON.parse(cameraSettings);
	}
```

**Comment by Bentix-cs** [comment]
> oh i think why the greenscreen didnt work, i didnt have this: https://github.com/jimgordon20/jim_g_green_screen but that doesnt explain why my customscreenshot command dont work. Also can you please add in dependency that ymap thanks

That is already included in the release, just have a look at the stream folder in the resource.

> I managed to fix the command. The command that i used and was in readme: `/customscreenshot 11 17 clothing male {"fov": 55, "rotation": { "x": 0, "y": 0, "z": 15}, "zPos": 0.26}`

This was also already fixed in the repository, I just didn't manage to put it in a new release.

**Comment by XyreDev** [comment]
oh damn, thats true but idk why it didnt stream it anyway, thanks!
