### ISSUE TITLE
Capturing alternate textures

### ISSUE THREAD

**Issue by Nanorithm** [Bentix-cs/fivem-greenscreener#6]
It doesn't seem there is a way to capture alternate textures, for example if I wanted to do `/customscreenshot 11 17 clothing male` it would only get the texture at ID 0, where I wanted the texture at ID 1 for that drawable for example.

**Comment by Bentix-cs** [comment]
Turn the include textures option in the config on.
Any other problems?

**Comment by Nanorithm** [comment]
Gof, thats a mega oversight on my part sorry! Nah that was it, awesome utility thanks!
