### ISSUE TITLE
[Suggestion] Add support for weapons

### ISSUE THREAD

**Issue by Nanorithm** [Bentix-cs/fivem-greenscreener#7]
I tried using this to get pictures of my addon weapons, but doing `/screenshotobject 453432689` (weapon_pistol) didn't do anything so I'm guessing that weapons are under a different category than objects and props.

**Comment by Bentix-cs** [comment]
Has been fixed in [1.6.1](https://github.com/Bentix-cs/fivem-greenscreener/releases/tag/1.6.1)
